name: Dist Files Size Diff (Comment)

on:
  workflow_run:
    workflows: ["Dist Files Size Diff"]
    types:
      - completed

jobs:
    dist-files-size-diff:
        runs-on: ubuntu-latest
        steps:
          - name: Download dist-size-diff artifact
            uses: actions/download-artifact@v4
            with:
              name: dist-size-diff
              run-id: ${{ github.event.workflow_run.id }}
              
          - name: Download pr-number artifact
            uses: actions/download-artifact@v4
            with:
              name: pr-number
              run-id: ${{ github.event.workflow_run.id }}
              
          - name: Read pr-number artifact to env var
            id: read-pr-number
            run: |
              echo "::set-output name=pr-number::$(cat ./pr-number)"
              
          - name: Comment on the pull request (if success)
            uses: marocchino/sticky-pull-request-comment@v2
            with:
              number: ${{ steps.read-pr-number.outputs.pr-number }}
              path: ./dist-size-diff.md
