name: Symfony UX Turbo

on:
    push:
        paths:
            - 'src/Turbo/**'
    pull_request:
        paths:
            - 'src/Turbo/**'

env:
    SYMFONY_REQUIRE: '>=5.4'

jobs:
    phpstan:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  extensions: zip

            - uses: ramsey/composer-install@v3
              with:
                  working-directory: src/Turbo

            - name: Install PHPUnit dependencies
              working-directory: src/Turbo
              run: vendor/bin/simple-phpunit --version

            - name: PHPStan
              working-directory: src/Turbo
              run: vendor/bin/phpstan analyse --no-progress

    tests:
        runs-on: ubuntu-latest
        strategy:
           fail-fast: false
           matrix:
               php-version: ['8.1', '8.3', '8.4']
               include:
                  - php-version: '8.1'
                    dependency-version: 'lowest'
                  - php-version: '8.3'
                    dependency-version: 'highest'
                  - php-version: '8.4'
                    dependency-version: 'highest'

        services:
            mercure:
                image: dunglas/mercure
                env:
                    SERVER_NAME: :3000
                    MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
                    MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
                    MERCURE_EXTRA_DIRECTIVES: |
                        anonymous
                        cors_origins *
                ports:
                    - 3000:3000

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}

            - name: Install symfony/flex
              run: composer global config allow-plugins.symfony/flex true && composer global require symfony/flex

            - name: Install dependencies with composer
              uses: ramsey/composer-install@v3
              with:
                working-directory: src/Turbo
                dependency-versions: ${{ matrix.dependency-version }}

            - name: Install JavaScript dependencies
              working-directory: src/Turbo/tests/app
              run: |
                php public/index.php importmap:install
                php public/index.php asset-map:compile

            - name: Create DB
              working-directory: src/Turbo/tests/app
              run: php public/index.php doctrine:schema:create

            - name: Run tests
              working-directory: src/Turbo
              run: |
                [ 'lowest' = '${{ matrix.dependency-version }}' ] && export SYMFONY_DEPRECATIONS_HELPER=weak
                vendor/bin/simple-phpunit
              env:
                  SYMFONY_DEPRECATIONS_HELPER: 'max[self]=1'
